apiVersion: v1
kind: Service
metadata:
  labels:
    app: laravel10-nodeport
  name: laravel10-nodeport
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: laravel10
  type: NodePort
status:
  loadBalancer: {}
